version: "3.3"
services:
  bot:
    build: .
    volumes:
      - ./cache:/var/cache/server-status-bot
    environment:
      - TELEGRAM_API_TOKEN
      - TELEGRAM_USER_ID
    network_mode: "host"
    restart: unless-stopped
